### ISSUE TITLE
Double click on units/waypoints does not work

### ISSUE THREAD

**Issue by NLDraakje** [ArmaAchilles/Achilles#441]
**Arma 3 Version:** `1.88` 
**CBA Version:** `v3.9.0.181012` 
**Achilles Version:** `1.4.2` 

**Mods:**
```
- CBA_A3
- Achilles
- NSS admin console
```

**Description:**
Creating a zeus module with nss admin in a file that does not have a zeus slot setup i.e. the standard escape on altis.
The double click for more options on units and on waypoints does not appear.
It seems this is an arma issue in general since it also does not work without achilles
**Steps to reproduce:**
launching a mission without a pre build zeus slot.
Using nss to create a zeus slot and then clicking interface.

**Where did the issue occur?**
- Environment: Self-Hosted Multiplayer / Singleplayer
- Mission: any that don't come with a pre-build zeus slot.

**Comment by oOKexOo** [comment]
I was able to reproduce the issue, however, there is nothing that we can do about it. The issue has to be fixed by the `NSS admin console` devs. The Zeus module they spawn does not get correctly initialized in SP/Self-Hosted MP. For a fix suggestion check out my comment on the script command [createUnit](https://community.bistudio.com/wiki/createUnit) (at the bottom of the page).
