### ISSUE TITLE
Paradrop Module

### ISSUE THREAD

**Issue by BnanaMan** [ArmaAchilles/Achilles#90]
It would be nice to have a paradrop module, which was able to teleport players/sides to a location/hight of your choosing. The teleported players than start falling from that hight. with a parachute on there back. as soon as they land the get their original backpack back. Its basicly like the mcc paradrop

**Comment by CreepPork** [comment]
A simpler solution, in my mind, would be to disable the message when moving players in Zeus. In that case it would allow to ALT drag them into the sky and let them fall with a parachute like objects and units. Don't know how would it actually work with actual players but I think that would be a better alternative than just creating another module.

Also this would sometimes satisfy my need for moving units to a specific place, rather than going to whole teleportation mechanic module.

This would need to work with changing the players altitude and giving them parachutes and keeping their backpacks etc. and maybe even allowing the Curator to delete player's corpses when they are dead and waiting to be re-spawned i.e. in vehicles which have been destroyed and I want to clean them up but cannot due to reason they are still "inside" the vehicle.

**Comment by oOKexOo** [comment]
Afaik it is hardcoded and thus cannot be changed. The teleport mechanics is the best we can have.

**Comment by CreepPork** [comment]
Well, damn :D

**Comment by oOKexOo** [comment]
I think about changing the teleport module rather than a new one. The current implementation is also useless for carriers.

**Comment by Tittoffer** [comment]
What about adding a setHight parameter on the teleportation module? Is that possible?

**Comment by oOKexOo** [comment]
Yeah I'm thinking about both a setHight parameter for teleport and a new HALO module.
